### ISSUE TITLE
test

### ISSUE THREAD

**Issue by liowalter** [swissbib/metadataNationalLicences#1]
test

**Comment by markusmiumueller** [comment]
Confirmation de réception

Merci et meilleures salutations
Markus

Markus Müller
Bern University Library, Digital Services & Open Science
+41 31 631 95 96 | markus.mueller@ub.unibe.ch<mailto:markus.mueller@ub.unibe.ch> | http://orcid.org/0000-0002-4226-2637
http://unibe.ch/ub/openscience
Hochschulstrasse 6, 3012 Bern, Switzerland

Am 05.06.2018 um 10:30 schrieb Lionel Walter <notifications@github.com<mailto:notifications@github.com>>:


test

**Comment by liowalter** [comment]
@markusmiumueller : thanks ! good to know
