### ISSUE TITLE
Rerodoc URL to PDF in 2020 files empty

### ISSUE THREAD

**Issue by mpbraendle** [swissbib/metadataNationalLicences#2]
The Rerodoc URL in the 2020 data is empty. We need this to attach the PDF to our repo.

**Comment by guenterh** [comment]
@liowalter kannst Du was machen?

**Comment by mpbraendle** [comment]
Ich denke, das Problem ist, dass die Förderung für Rerodoc nicht mehr besteht und bei SONAR es noch offene Fragen gibt. Wir warten mal die Antwort des Konsortiums ab.

**Comment by liowalter** [comment]
@mpbraendle : ja genau. Die PDF sind noch nicht in RERO DOC aber sollen schon bald dort landen.

**Comment by liowalter** [comment]
@mpbraendle : The PDF's have been ingested in RERO DOC. I updated the lists in this repo with the url to the fulltext, as well as on https://consortium.ch/open-access/?lang=en.

**Comment by mpbraendle** [comment]
Thank you, @liowalter !

**Comment by mpbraendle** [comment]
@liowalter The current uzh.csv file has 15 lines less than the previous one - is there a reason for this?

**Comment by liowalter** [comment]
@mpbraendle There were some problems with the pdf's for these articles. Either there were corrupted or not available on the publisher platform or in the publisher deliveries. That's the reason. At best, you can process them manually if you want.

**Comment by mpbraendle** [comment]
ty @liowalter - we will work with what we have now.
